Repository openshift/gcp-project-operator, pull requests merged in 2020-04, with the labels that each got.

#45 Handle deletion before error check
  pkg/controller/projectreference/projectreference_adapter.go
  pkg/controller/projectreference/projectreference_adapter_test.go
  pkg/controller/projectreference/projectreference_controller.go
  pkg/controller/projectreference/projectreference_controller_test.go
Labels: approved, lgtm

#48 Refactor ProjectClaim controller and tests
  Makefile
  go.mod
  go.sum
  pkg/controller/projectclaim/projectclaim_controller.go
  pkg/controller/projectclaim/projectclaim_controller_test.go
  pkg/controller/projectclaim/projectclaimadapter.go
  pkg/controller/projectclaim/projectclaimadapter_test.go
  pkg/gcpclient/client.go
  pkg/util/mocks/projectclaim/customeresourceadapter.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/modules.txt
Labels: approved, lgtm

#53 Remove outdated information from README
  README.md
Labels: approved, lgtm

#54 Add documentation
  CONTRIBUTING.md
  docs/README.md
  docs/analyze.md
  docs/api.md
  docs/building.md
  docs/debug.md
  docs/design.md
  docs/development.md
  docs/gcpconfig.md
  docs/testing.md
  docs/troubleshooting.md
  docs/userstory.md
Labels: lgtm

#56 Enable regions with sufficient quota
  pkg/controller/projectreference/projectreference_adapter.go
Labels: approved, lgtm

#57 Document minimum quota requirements
  pkg/controller/projectreference/projectreference_adapter.go
Labels: approved, lgtm

#59 Improve documentation
  Makefile
  README.md
  coverage_badge.png
  docs/README.md
  docs/analyze.md
  docs/api.md
  docs/design.md
  docs/development.md
  docs/gcpconfig.md
  docs/images/architecture.png
  docs/images/configmap_secret.png
  docs/images/gcpprojectoperator.png
  docs/images/requiresetup.png
  docs/testing.md
  docs/userstory.md
Labels: approved, lgtm

#58 Change ProjectReference adapter test package
  pkg/controller/projectreference/projectreference_adapter.go
  pkg/controller/projectreference/projectreference_adapter_test.go
  pkg/controller/projectreference/projectreference_controller.go
  pkg/controller/projectreference/projectreference_controller_test.go
Labels: approved, lgtm

#60 Add link to video
  README.md
Labels: approved, lgtm

#52 projectreference controller communicates errors
  go.sum
  pkg/apis/gcp/v1alpha1/common_types.go
  pkg/apis/gcp/v1alpha1/projectclaim_types.go
  pkg/apis/gcp/v1alpha1/projectreference_types.go
  pkg/apis/gcp/v1alpha1/zz_generated.deepcopy.go
  pkg/condition/conditions.go
  pkg/condition/conditions_suite_test.go
  pkg/condition/conditions_test.go
  pkg/condition/mock/conditions.go
  pkg/controller/projectclaim/projectclaim_controller.go
  pkg/controller/projectclaim/projectclaimadapter.go
  pkg/controller/projectclaim/projectclaimadapter_test.go
  pkg/controller/projectreference/projectreference_adapter.go
  pkg/controller/projectreference/projectreference_adapter_test.go
  pkg/controller/projectreference/projectreference_controller.go
  pkg/controller/projectreference/projectreference_controller_test.go
  pkg/util/mocks/projectclaim/customeresourceadapter.go
  pkg/util/mocks/structs/projectclaim.go
Labels: approved

#61 Refactor SetCondition
  pkg/condition/conditions.go
  pkg/condition/conditions_test.go
Labels: approved, lgtm
