Repository openshift/gcp-project-operator, pull requests merged in 2020-03, with the labels that each got.

#16 OSD-2924: migrate billing account to configmap, configmap structure is refactored
  README.md
  go.mod
  go.sum
  pkg/configmap/configmap.go
  pkg/configmap/configmap_test.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeploymet_controller_test.go
  pkg/util/mocks/structs/core.go
  pkg/util/util.go
  pkg/util/utils_test.go
Labels: lgtm, size/L

#18 OSD-2924: go mod vendor
  vendor/github.com/emicklei/go-restful/.gitignore
  vendor/github.com/emicklei/go-restful/CHANGES.md
  vendor/github.com/emicklei/go-restful/README.md
  vendor/github.com/emicklei/go-restful/container.go
  vendor/github.com/emicklei/go-restful/curly.go
  vendor/github.com/emicklei/go-restful/custom_verb.go
  vendor/github.com/emicklei/go-restful/path_processor.go
  vendor/github.com/emicklei/go-restful/response.go
  vendor/github.com/emicklei/go-restful/route.go
  vendor/github.com/emicklei/go-restful/web_service.go
  vendor/github.com/imdario/mergo/.travis.yml
  vendor/github.com/imdario/mergo/merge.go
  vendor/github.com/mitchellh/mapstructure/.travis.yml
  vendor/github.com/mitchellh/mapstructure/CHANGELOG.md
  vendor/github.com/mitchellh/mapstructure/LICENSE
  vendor/github.com/mitchellh/mapstructure/README.md
  vendor/github.com/mitchellh/mapstructure/decode_hooks.go
  vendor/github.com/mitchellh/mapstructure/error.go
  vendor/github.com/mitchellh/mapstructure/go.mod
  vendor/github.com/mitchellh/mapstructure/mapstructure.go
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_03_config-operator_01_operatorhub.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_03_config-operator_01_proxy.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_build.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_console.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_dns.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_featuregate.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_image.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_network.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_project.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_scheduler.crd.yaml
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_console.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_operatorhub.go
  vendor/github.com/openshift/api/config/v1/types_project.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/types_tlssecurityprofile.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, size/XXL

#20 dummy commit to check pipeline
  README.md
Labels: size/XS

#21 Add PendingProject claim status
  pkg/apis/gcp/v1alpha1/projectclaim_types.go
Labels: size/XS

#22 Document workflow with ProjectClaim
  README.md
Labels: lgtm, size/M

#23 Added ProjectID to ProjectClaim when Project Reference is READY
  README.md
  deploy/crds/gcp_v1alpha1_projectclaim_crd.yaml
  pkg/apis/gcp/v1alpha1/projectclaim_types.go
  pkg/controller/projectreference/projectreference_controller.go
  pkg/controller/projectreference/projectreference_controller_test.go
Labels: size/M

#17 Ensure project id meets gcp requirements
  go.mod
  pkg/controller/projectreference/projectreference_adapter.go
  pkg/controller/projectreference/projectreference_adapter_test.go
  vendor/github.com/google/btree/btree_mem.go
  vendor/golang.org/x/net/html/atom/gen.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/charmap/maketables.go
  vendor/golang.org/x/text/encoding/htmlindex/gen.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/encoding/japanese/maketables.go
  vendor/golang.org/x/text/encoding/korean/maketables.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/maketables.go
  vendor/golang.org/x/text/encoding/traditionalchinese/maketables.go
  vendor/golang.org/x/text/internal/language/compact/gen.go
  vendor/golang.org/x/text/internal/language/compact/gen_index.go
  vendor/golang.org/x/text/internal/language/compact/gen_parents.go
  vendor/golang.org/x/text/internal/language/gen.go
  vendor/golang.org/x/text/internal/language/gen_common.go
  vendor/golang.org/x/text/language/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/golang.org/x/tools/internal/imports/mkindex.go
  vendor/golang.org/x/tools/internal/imports/mkstdlib.go
  vendor/modules.txt
Labels: do-not-merge/hold, lgtm, size/XXL

#25 Fix namespace on SA
  deploy/uhc_service_account.yaml
Labels: size/XS

#26 Update OWNERS to include sre-platform-leads
  OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm, size/S

#27 Refactor ref controller
  pkg/controller/projectreference/projectreference_adapter.go
  pkg/controller/projectreference/projectreference_adapter_test.go
  pkg/controller/projectreference/projectreference_controller.go
  pkg/util/mocks/status-writer.go
Labels: approved, lgtm, size/L

#29 Added configmap permissions for OCM
  deploy/uhc_cluster_role.yaml
Labels: approved, lgtm, size/XS

#30 Fix the configmap instructions
  README.md
Labels: approved, lgtm, size/S

#31 Revert "ProjectClaim controller maintains ProjectClaim state"
  go.mod
  pkg/controller/projectclaim/customresourceadapter.go
  pkg/controller/projectclaim/customresourceadapter_test.go
  pkg/controller/projectclaim/projectclaim_controller.go
  pkg/controller/projectclaim/projectclaim_controller_test.go
Labels: approved, lgtm, size/L

#32 Migrated to new secret name
  pkg/controller/projectreference/projectreference_adapter.go
  pkg/controller/projectreference/projectreference_controller.go
  pkg/util/util.go
  pkg/util/utils_test.go
Labels: approved, lgtm, size/S

#33 ProjectClaim status
  pkg/controller/projectclaim/customresourceadapter.go
  pkg/controller/projectclaim/customresourceadapter_test.go
  pkg/controller/projectclaim/projectclaim_controller.go
  pkg/controller/projectclaim/projectclaim_controller_test.go
  pkg/controller/projectreference/projectreference_adapter.go
  pkg/util/mocks/structs/projectclaim.go
Labels: approved, lgtm, size/L

#34 Add sha to the version
  hack/app_sre_create_image_catalog.sh
  hack/generate-operator-bundle.py
Labels: approved, lgtm, size/XS

#35 ClusterDeploymentController can be turned off
  pkg/configmap/configmap.go
  pkg/configmap/configmap_test.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeploymet_controller_test.go
  pkg/util/mocks/structs/core.go
Labels: approved, lgtm

#37 Refactor GCP project creation
  pkg/controller/projectreference/projectreference_adapter.go
  pkg/controller/projectreference/projectreference_adapter_test.go
  pkg/controller/projectreference/projectreference_controller.go
  pkg/controller/projectreference/projectreference_controller_test.go
Labels: approved, lgtm

#40 Updated secret name on CD
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeploymet_controller_test.go
Labels: approved, lgtm

#41 Add auth secret setup info
  README.md
Labels: approved, lgtm

#39 Don't process if ProjectReference if status is not PendingProject
  pkg/controller/projectreference/projectreference_adapter_test.go
  pkg/controller/projectreference/projectreference_controller.go
  pkg/controller/projectreference/projectreference_controller_test.go
  pkg/util/mocks/structs/projectclaim.go
Labels: approved, lgtm

#36 GCP Project cleanup
  pkg/controller/projectreference/projectreference_adapter.go
  pkg/controller/projectreference/projectreference_adapter_test.go
  pkg/controller/projectreference/projectreference_controller.go
  pkg/controller/projectreference/projectreference_controller_test.go
  pkg/gcpclient/client.go
  pkg/util/mocks/gcpclient/client.go
  pkg/util/util.go
  pkg/util/utils_test.go
Labels: approved, lgtm

#43 Reduce length of ProjectID to 10
  pkg/controller/projectreference/projectreference_adapter.go
Labels: approved, lgtm

#38 ProjectClaim controller communicates errors and updates ProjectClaimCondition
  pkg/controller/projectclaim/customresourceadapter.go
  pkg/controller/projectclaim/customresourceadapter_test.go
  pkg/controller/projectclaim/projectclaim_controller.go
Labels: approved, lgtm

#44 Add finalizer before GCP project setup
  pkg/controller/projectclaim/customresourceadapter.go
  pkg/controller/projectclaim/customresourceadapter_test.go
  pkg/controller/projectclaim/projectclaim_controller.go
  pkg/controller/projectreference/projectreference_controller.go
  pkg/controller/projectreference/projectreference_controller_test.go
Labels: approved, lgtm
