Repository openshift/gcp-project-operator, pull requests merged in 2020-02, with the labels that each got.

#3 Projectclaim crd
  deploy/cluster_role.yaml
  deploy/crds/gcp_v1alpha1_projectclaim_cr.yaml
  deploy/crds/gcp_v1alpha1_projectclaim_crd.yaml
  go.mod
  go.sum
  pkg/apis/addtoscheme_gcp_v1alpha1.go
  pkg/apis/gcp/groups.go
  pkg/apis/gcp/v1alpha1/doc.go
  pkg/apis/gcp/v1alpha1/projectclaim_types.go
  pkg/apis/gcp/v1alpha1/register.go
  pkg/apis/gcp/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/gcp/v1alpha1/zz_generated.openapi.go
  vendor/github.com/golang/mock/gomock/call.go
  vendor/github.com/golang/mock/gomock/callset.go
  vendor/github.com/golang/mock/gomock/controller.go
  vendor/github.com/golang/mock/gomock/matchers.go
  vendor/golang.org/x/tools/go/ast/astutil/imports.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_portable.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_unix.go
  vendor/golang.org/x/tools/internal/gopathwalk/walk.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/imports.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/imports/mod_cache.go
  vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
  vendor/modules.txt
Labels: size/XXL

#4 Add files for pipeline
  Makefile
  OWNERS
  build/Dockerfile
  config/config.go
  config/templates/gcp-project-operator-csv-template.yaml
  deploy/operator.yaml
  deploy/prometheus/prometheus-k8s-role.yaml
  deploy/prometheus/prometheus-k8s-rolebinding.yaml
  deploy/uhc_cluster_role.yaml
  deploy/uhc_cluster_role_binding.yaml
  deploy/uhc_service_account.yaml
  hack/app_sre_build_deploy.sh
  hack/app_sre_create_image_catalog.sh
  hack/app_sre_pr_check.sh
  hack/generate-operator-bundle.py
  hack/olm-registry/olm-artifacts-template.yaml
  hack/validate_yaml.py
  project.mk
  standard.mk
Labels: lgtm, size/XL

#8 add functional team as reviewers
  OWNERS
Labels: lgtm, size/XS

#7 Generate project id
  go.mod
  go.sum
  pkg/controller/add_projectreference.go
  pkg/controller/projectreference/projectreference_controller.go
  pkg/controller/projectreference/projectreference_controller_test.go
  pkg/controller/projectreference/projectreference_suite_test.go
  pkg/util/mocks/cr-client.go
  pkg/util/mocks/structs/builders.go
  pkg/util/mocks/structs/projectreference.go
Labels: do-not-merge/hold, size/L

#11 Add local quickstart to docs
  README.md
Labels: lgtm, size/M

#12 OSD-2888: get orgParentFolderID from configmap
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeploymet_controller_test.go
  pkg/util/mocks/structs/core.go
  pkg/util/util.go
  pkg/util/utils_test.go
Labels: lgtm, size/L

#9 Unpin openshift/api dep and run `go mod tidy`
  go.mod
  go.sum
Labels: size/M
